apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-two
  namespace: p2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-two
  template:
    metadata:
      labels:
        app: app-two
    spec:
      containers:
      - name: whoami
        image: traefik/whoami:v1.12.0@sha256:c4717a8d1f0134a7444e24f881160e033991f23027c6c5a9a3f8fd22e70d1d44
        ports:
        - containerPort: 80
