# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX = "generic/alpine318"

Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.provider :libvirt

  config.vm.define "guebersoS" do |server|
    server.vm.hostname = "guebersoS"
    server.vm.network "private_network", ip: "192.168.56.110", libvirt__network_name: "vagrant-libvirt"

    server.vm.provider "libvirt" do |lv|
      lv.cpus = 1
      lv.memory = 1024
    end

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "confs/playbooks/server.yml"
      ansible.verbose = "v"
    end
  end
end
