Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", type: "rsync"

  config.vm.define "pnaessenS" do |server|
    server.vm.box = "generic/debian12"
    server.vm.hostname = "pnaessenS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
      lv.driver = "kvm"
    end

    server.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.limit = 'all'
      ansible.groups = {
        "k3s_servers" => ["pnaessenS"]
      }
    end
  end
end
