Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant"

  config.vm.define "pnaessenS" do |server|
    server.vm.box = "generic/debian12"
    server.vm.hostname = "pnaessenS"
    server.vm.network "private_network", ip: "192.168.56.110"

    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
      lv.driver = "qemu"
    end

    server.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end
  end

  config.vm.define "pnaessenSW" do |worker|
    worker.vm.box = "generic/debian12"
    worker.vm.hostname = "pnaessenSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
      lv.driver = "qemu"
    end

    worker.vm.provider "virtualbox" do |vb|
      vb.memory = 1024
      vb.cpus = 1
    end

    worker.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
      ansible.groups = {
        "pnaessenS" => ["pnaessenS"],
        "pnaessenSW" => ["pnaessenSW"]
      }
    end
  end
end
