Vagrant.configure("2") do |config|
  # Base image used for both VMs: official Debian 12 box, confirmed to
  # resolve to the correct x86_64 architecture for the libvirt provider
  config.vm.box = "debian/bookworm64"
  # Disables the default NFS shared folder between the host and each VM.
  # Not needed for this project (no live file editing required inside the VMs), and avoids an /etc/exports permission error seen during setup.
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define "lbuissonS" do |server|
    server.vm.hostname = "lbuissonS"

    # Private network between the two VMs, on a dedicated subnet.
    # libvirt__network_name forces both VMs onto the SAME virtual network/bridge 
    server.vm.network "private_network", ip: "192.168.57.110", libvirt__network_name: "k3s_network"
    server.vm.provider "libvirt" do |lv|
      lv.memory = 1024 # RAM in MB, within the 512–1024 MB spec range
      lv.cpus = 1
    end

    server.trigger.after :up do |trigger|
      trigger.run = { inline:
        "sh -c \"cat .vagrant/machines/lbuissonS/libvirt/private_key | vagrant ssh lbuissonSW -- 'cat > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa'\""
      }
    end

  end

  config.vm.define "lbuissonSW" do |agent|
    agent.vm.hostname = "lbuissonSW"
    agent.vm.network "private_network", ip: "192.168.57.111", libvirt__network_name: "k3s_network"
    agent.vm.provider "libvirt" do |lv|
      lv.memory = 1024
      lv.cpus = 1
    end

    agent.trigger.after :up do |trigger|
      trigger.run = { inline:
        "sh -c \"cat .vagrant/machines/lbuissonSW/libvirt/private_key | vagrant ssh lbuissonS -- 'cat > ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa'\""
      }
    end

  end
end