---
- name: Configure K3s Worker Node on Debian
  hosts: k3s_workers
  become: yes

  tasks:
    - name: Configure DNS to use default gateway (host) to resolve domains at 42
      ansible.builtin.shell: |
        gateway_ip=$(ip route show | grep default | awk '{print $3}')
        if [ ! -z "$gateway_ip" ]; then
          echo "nameserver $gateway_ip" > /etc/resolv.conf
        fi
      changed_when: false

    - name: Update apt cache and install curl
      ansible.builtin.apt:
        update_cache: yes
        name:
          - curl
        state: present

    - name: Create user pnaessen
      ansible.builtin.user:
        name: pnaessen
        shell: /bin/bash
        groups: sudo
        append: yes
        state: present

    - name: Configure passwordless sudo for user pnaessen
      ansible.builtin.copy:
        content: "pnaessen ALL=(ALL) NOPASSWD:ALL"
        dest: /etc/sudoers.d/pnaessen
        mode: '0440'

    - name: Set up passwordless SSH key for user pnaessen
      ansible.builtin.file:
        path: /home/pnaessen/.ssh
        state: directory
        owner: pnaessen
        group: pnaessen
        mode: '0700'

    - name: Copy authorized_keys from vagrant to pnaessen
      ansible.builtin.copy:
        src: /home/vagrant/.ssh/authorized_keys
        dest: /home/pnaessen/.ssh/authorized_keys
        remote_src: yes
        owner: pnaessen
        group: pnaessen
        mode: '0600'

    - name: Check if K3s agent is already installed
      ansible.builtin.stat:
        path: /usr/local/bin/k3s-agent
      register: k3s_binary

    - name: Download K3s install script
      ansible.builtin.get_url:
        url: https://get.k3s.io
        dest: /tmp/k3s-install.sh
        mode: "0755"
      when: not k3s_binary.stat.exists

    - name: Copy K3s node token from the host machine to worker VM
      ansible.builtin.copy:
        src: /tmp/k3s-node-token
        dest: /tmp/k3s-node-token
        mode: '0600'

    - name: Read K3s token
      ansible.builtin.slurp:
        src: /tmp/k3s-node-token
      register: worker_k3s_token_slurp

    - name: Wait for K3s server API to be reachable
      ansible.builtin.wait_for:
        host: 192.168.56.110
        port: 6443
        state: started
        timeout: 300

    - name: Install and start K3s in agent (worker) mode
      ansible.builtin.command:
        cmd: >
          /tmp/k3s-install.sh agent
          --node-ip=192.168.56.111
      environment:
        K3S_URL: "https://192.168.56.110:6443"
        K3S_TOKEN: "{{ worker_k3s_token_slurp.content | b64decode | trim }}"
      when: not k3s_binary.stat.exists
